version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-node
    restart: always
    image: clean-node
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./src:/usr/src/clean-node/src
      - ./package.json:/usr/src/clean-node/package.json
    ports:
      - 3333:3333
      - 9222:9222
    links:
      - mongo
    depends_on:
      - mongo
