version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-node
    command: npm start
    volumes:
      - ./src:/usr/src/clean-node
    ports:
      - "3333:3333"
    links:
      - mongo
